name: routes_flutter_web
description: Routes Flutter Web
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  auto_route: ^8.3.0
  flutter:
    sdk: flutter
  get: ^4.6.6
  url_strategy: ^0.2.0

dev_dependencies:
  auto_route_generator: 8.1.0
  build_runner: 
  flutter_lints: ^4.0.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
